- id: flake8-nb
  name: flake8-nb
  description: "flake8 checking for jupyter notebooks"
  entry: flake8-nb
  language: python
  language_version: python3
  require_serial: true
  types: [file]
  files: \.(py|ipynb)$
