name: "Trigger-Binder-build"
on:
  push:
    branches:
      - main

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: s-weigand/flake8-nb
