name: "Update pre-commit config"
on:
  schedule:
    - cron: "0 7 * * 1" # At 07:00 on each Monday.
  workflow_dispatch:

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Update pre-commit config packages
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            pip install pre-commit
            pre-commit autoupdate || (exit 0);
            pre-commit run -a || (exit 0);
          COMMIT_MESSAGE: "MAINT Update pre-commit config"
          PR_BRANCH_NAME: "pre-commit-config-update-${PR_ID}"
          PR_TITLE: "MAINT Update pre-commit config"
